site_name: Lennart Wittkuhn's Atom configurations
site_author: Lennart Wittkuhn
repo_url: https://github.com/lnnrtwttkhn/.atom
site_url: https://lnnrtwttkhn.github.io/.atom/
repo_name: lnnrtwttkhn/.atom
docs_dir: docs
copyright: 'Copyright &copy 2020 Lennart Wittkuhn'
nav:
  - Home: index.md
  - Environments: environments.md
markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        baselevel: 1
        permalink: true
        separator: "_"
        toc_depth: 3
        anchorlink: false
theme:
    name: material
    language: en
    palette:
        primary: green
        accent: white
plugins:
    - search
